### ISSUE TITLE
About LICENSE

### ISSUE THREAD

**Issue by maruilian11** [ebobby/tracing.js#3]
Hi! I'm from [cdnjs](https://github.com/cdnjs/cdnjs). Recently, we want to host your popular lib. But we need to confirm the license of it with you first. Can we see you lib as MIT license? Thanks.
https://github.com/cdnjs/cdnjs/pull/11979

**Comment by PeterDaveHello** [comment]
Isn't this clear enough: https://github.com/ebobby/tracing.js/blob/master/COPYING ?

**Comment by maruilian11** [comment]
Thanks. Sorry didn't notice it before.

**Comment by PeterDaveHello** [comment]
Except this part: `Except as contained in this notice, the name(s) of the above copyright holders shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Software without prior written authorization.`, it's totally **MIT** license.
